name: nightly

on:
  workflow_dispatch:
  schedule:
    - cron:  '30 1 1 * *'
  release:
    types: [published]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: ^1.23
      id: go

    - name: Install staticcheck
      run: go install honnef.co/go/tools/cmd/staticcheck@latest

    - name: Install govulncheck
      run: go install golang.org/x/vuln/cmd/govulncheck@latest

    - name: Build
      run: make build-all

    - name: Upload Linux artifact
      uses: actions/upload-artifact@v4
      with:
        path: dist/development/linux/uhppoted-rest
        name: uhppoted-rest_linux-nightly

    - name: Upload MacOS Intel artifact
      uses: actions/upload-artifact@v4
      with:
        path: dist/development/darwin-x64/uhppoted-rest
        name: uhppoted-rest_darwin-x64-nightly

    - name: Upload MacOS Apple silicon artifact
      uses: actions/upload-artifact@v4
      with:
        path: dist/development/darwin-arm64/uhppoted-rest
        name: uhppoted-rest_darwin-arm64-nightly

    - name: Upload Windows artifact
      uses: actions/upload-artifact@v4
      with:
        path: dist/development/windows/uhppoted-rest.exe
        name: uhppoted-rest_windows-nightly.exe

    - name: Upload ARM artifact
      uses: actions/upload-artifact@v4
      with:
        path: dist/development/arm/uhppoted-rest
        name: uhppoted-rest_arm-nightly

    - name: Upload ARMv7 artifact
      uses: actions/upload-artifact@v4
      with:
        path: dist/development/arm7/uhppoted-rest
        name: uhppoted-rest_arm7-nightly

    - name: Upload ARMv6 artifact
      uses: actions/upload-artifact@v4
      with:
        path: dist/development/arm6/uhppoted-rest
        name: uhppoted-rest_arm6-nightly
